title: "Errol Pascua"
description: "Embedded / Security Engineer — Resume & Projects"
theme: minima

minima:
  skin: dark

author: Errol Pascua

header_pages:
  - resume.md
  - projects.md
  - about.md
  - linkedin.md
